language: java
jdk: oraclejdk8

sudo: false # faster builds
install: true
script: mvn clean package sonar:sonar

cache:
  directories:
  - $HOME/.m2

notifications:
    slack: deoliveirasaurin:8QEuNZTItMPifw7e0scBDXtU#difcover-plugin-maven

